package ru.roman.puzzle;

/**
 * Generated by the IBM IDL-to-Java compiler, version 1.0

 * from F:\TestRoot\apps\a1\\units\include\PolicyHome.idl

 * Wednesday, June 17, 1998 6:44:40 o'clock AM GMT+00:00
 */
public class Puzzle5Comment {

   //  \\units - illegal unicode escape



    /* (Operators not supported yet)
    if ("+-*///&|!=".indexOf(ch) >= 0)         - не видимое завершение коммента
}
