package ru.roman.puzzle;

import java.util.Arrays;

/**
 * Generated by the IBM IDL-to-Java compiler, version 1.0

 * from F:\TestRoot\apps\a1\\units\include\PolicyHome.idl                 - illegal Unicode symbol

 * Wednesday, June 17, 1998 6:44:40 o'clock AM GMT+00:00
 */
class UlgyComments {

    public static void main(String[] args) {
        //  \\units - illegal unicode escape

        http: //myworld.com:8080/puzzles.html    // just legal, URL = label + comment

            /* (Operators not supported yet)
        if ("+-*///&|!=".indexOf(ch) >= 0)         - не видимое завершение коммента

        for (int i : Arrays.asList(1, 2, 3));     // just few iterations
    }
}
